// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabConteudoAcademico.Data;

#nullable disable

namespace TrabConteudoAcademico.Migrations
{
    [DbContext(typeof(PostagemDbContext))]
    [Migration("20231129113807_migration inicial")]
    partial class migrationinicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Postagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Postagem");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Descricao = "teste",
                            IdUsuario = 1
                        },
                        new
                        {
                            Id = 1002,
                            Descricao = "teste",
                            IdUsuario = 1
                        },
                        new
                        {
                            Id = 1003,
                            Descricao = "teste",
                            IdUsuario = 1
                        },
                        new
                        {
                            Id = 1004,
                            Descricao = "teste",
                            IdUsuario = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
